### PR TITLE
add sktorrent usernames

### PR DESCRIPTION
**Pull request by sanAkdam**

### CODE REVIEW

**Comment by jayvdb** [comment]
I doubt a username list is especially useful as a password list, but @duyetdev will be a better judge of that.

More importantly, it seems the process to create this file has broken the encoding.  There are lots of entries like `LukÃ¡Â¹333`.  I do not see the same problem with the password list added in https://github.com/duyetdev/bruteforce-database/pull/2 from the same source.

**Comment by jayvdb** [comment]
And now you have merge conflict to resolve.

**Comment by duyetdev** [comment]
@jayvdb I agree with you. username list is especially useful as a password.

**Comment by jayvdb** [comment]
I said

> I doubt a username list is especially useful as a password list

Also, the file has encoding problems.  It is a bad commit.

**Pull request merged**
